// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type SearchHTTPServer interface {
	MustSearch(context.Context, *MustSearchRequest) (*MustSearchReply, error)
}

func RegisterSearchHTTPServer(s *http.Server, srv SearchHTTPServer) {
	r := s.Route("/")
	r.POST("/search/must", _Search_MustSearch0_HTTP_Handler(srv))
}

func _Search_MustSearch0_HTTP_Handler(srv SearchHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MustSearchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.search.v1.Search/MustSearch")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MustSearch(ctx, req.(*MustSearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MustSearchReply)
		return ctx.Result(200, reply)
	}
}

type SearchHTTPClient interface {
	MustSearch(ctx context.Context, req *MustSearchRequest, opts ...http.CallOption) (rsp *MustSearchReply, err error)
}

type SearchHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchHTTPClient(client *http.Client) SearchHTTPClient {
	return &SearchHTTPClientImpl{client}
}

func (c *SearchHTTPClientImpl) MustSearch(ctx context.Context, in *MustSearchRequest, opts ...http.CallOption) (*MustSearchReply, error) {
	var out MustSearchReply
	pattern := "/search/must"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.search.v1.Search/MustSearch"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
